cache: bundler
before_install: gem install bundler
script: bundle exec jekyll build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: _site
  on:
    branch: master
