name: Dana McCurdy
markdown: kramdown
permalink: pretty
url: http://danamccurdy.com
gems:
  - jekyll-sitemap
defaults:
  - values:
      layout: page
  - scope:
      type: posts
    values:
      layout: post
kramdown:
  input: GFM
prose:
  rooturl: _posts
  metadata:
    _posts:
      - name: title
        field:
          element: text
      - name: category
        field:
          element: select
          options:
            - name: Life
              value: life
            - name: Love
              value: love
