# Global site metadata
# For SEO Tag plugin (https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md)
title: Dana McCurdy
description: For me, life is about learning and creative expression. My goal as a human being and a professional is to promote and facilitate these in every way I can.
url: https://danamccurdy.com
author: Dana McCurdy
logo: /assets/favicon.png

# Configuration (https://jekyllrb.com/docs/configuration/)
defaults:
  - values:
      image: /assets/portrait.jpg
      layout: default
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      path: poems
    values:
      layout: posts
      title: Poems
incremental: true
kramdown: # https://kramdown.gettalong.org/options.html
  hard_wrap: true
permalink: pretty
livereload: true
pagination:
  enabled: true
  sort_reverse: true

# Prose (https://github.com/prose/prose/wiki/Prose-Configuration)
prose:
  ignore:
    - _config.yml
    - _includes
    - _layouts
    - .*
    - assets
    - bin
    - CNAME
    - Gemfile
    - Gemfile.lock
    - poems
    - README.md
  media: assets
  siteurl: https://danamccurdy.com
  metadata:
    _posts:
      - name: title
        field:
          element: text
          label: Title
          help: "The title of the post, page, or document. This is usually displayed in browsers, link previews, and headings on the website. Page titles also show up in the navbar and home page previews."
          placeholder: REQUIRED
      - name: description
        field:
          element: text
          label: Description
          help: "A short description of the page's content. This defaults to the excerpt, so you shouldn't need to change it normally. Unlike the excerpt, other sites can use this for previews."
      - name: image
        field:
          element: text
          label: Image URL
          help: URL to an image associated with the post, page, or document (e.g., /assets/page-pic.jpg). The image URL must be absolute or root-relative. Defaults to the portrait photo. Posts display their image automatically, other documents only use them for previews. Images must be owned by you or licensed for free use.
      - name: categories
        field:
          element: multiselect
          label: Post Categories
          help: The list of categories to which this post belongs. If this is left blank, the post will be hidden from the post listings.
          placeholder: REQUIRED
          options:
            - life
            - love
          value: life
      - name: tags
        field:
          element: multiselect
          label: Post Tags
          help: The list of tags for this post. Tags are optional, overlapping, case sensitive, and hidden from the website.
          alterable: true
      - name: centered
        field:
          element: checkbox
          label: Centered Text
          help: Enable to center the entire post.
      - name: published
        field:
          element: checkbox
          label: Published
          help: "Disable to avoid automatically publishing the page. After the post's first commit, this can be changed through the editor's Published button."
          value: true
