# Global site metadata
# For Feed and SEO Tag plugins (https://github.com/jekyll/jekyll-seo-tag#usage)
title: Dana McCurdy
description: For me, life is about learning and creative expression. My goal as a human being and a professional is to promote and facilitate these in every way I can.
url: http://danamccurdy.com
logo: /assets/favicon.png
social:
  links:
    - https://www.facebook.com/danamcc
    - https://plus.google.com/114358713485860267704
    - https://www.youtube.com/channel/UC1y3uwrvlA8TqjNJHEi7dpA
    - https://www.linkedin.com/in/dana-mccurdy-b68872a2
    - https://soundcloud.com/danam

# Configuration (https://jekyllrb.com/docs/configuration/)
defaults:
  - values:
      image: /assets/portrait.jpg
      layout: page
  - scope:
      type: posts
    values:
      layout: post
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
host: 0.0.0.0
incremental: true
kramdown: # http://kramdown.gettalong.org/options.html
  hard_wrap: true
permalink: pretty

# Prose (https://github.com/prose/prose/wiki/Prose-Configuration)
prose:
  ignore:
    - _layouts
    - assets
    - bin
    - poems
    - '*.html'
    - .*
    - CNAME
    - Gemfile
  media: assets
  metadata:
    _posts:
      - name: title
        field:
          element: text
          label: Title
          help: The title of the poem in poem listings and tabs.
      - name: categories
        field:
          element: multiselect
          label: Categories
          help: Categories to display the poem in.
          alterable: false
          options:
            - name: Life
              value: life
            - name: Love
              value: love
      - name: image
        field:
          element: text
          label: Image URL
          help: An image to be displayed by the poem. The image URL must be absolute or root-relative.
      - name: centered
        field:
          element: checkbox
          label: Centered
          help: Enable to center the entire poem against the left border.
