title: Dana McCurdy
permalink: pretty
description: For me, life is about learning and creative expression. My goal as a human being and a professional is to promote and facilitate these in every way I can.
url: http://danamccurdy.com
author:
  name: Dana McCurdy
  uri: http://danamccurdy.com
  email: danamcc221@gmail.com
facebook:
  publisher: https://www.facebook.com/danamcc
social:
  links:
    - https://www.facebook.com/danamcc
    - https://plus.google.com/114358713485860267704
    - https://www.youtube.com/channel/UC1y3uwrvlA8TqjNJHEi7dpA
    - https://www.linkedin.com/in/dana-mccurdy-b68872a2
    - https://soundcloud.com/danam
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
defaults:
  - values:
      layout: page
  - scope:
      type: posts
    values:
      layout: post
incremental: true
kramdown:
  hard_wrap: true
prose:
  rooturl: _posts
  metadata:
    _posts:
      - name: title
        field:
          element: text
          label: Title
          help: The title of the post in post listings and tabs.
      - name: categories
        field:
          element: multiselect
          label: Categories
          help: Categories to display the post in.
          alterable: false
          options:
            - name: Life
              value: life
            - name: Love
              value: love
      - name: centered
        field:
          element: checkbox
          label: Centered
          help: Enable to center the entire post against the left border.
