name: Dana McCurdy
permalink: pretty
description: For me, life is about learning and creative expression. My goal as a human being and a professional is to promote and facilitate these in every way I can.
url: http://danamccurdy.com
author:
  name: Dana McCurdy
  uri: http://danamccurdy.com
  email: danamcc221@gmail.com
gems:
  - jekyll-feed
  - jekyll-sitemap
defaults:
  - values:
      layout: page
  - scope:
      type: posts
    values:
      layout: post
prose:
  rooturl: _posts
  metadata:
    _posts:
      - name: title
        field:
          element: text
      - name: category
        field:
          element: select
          options:
            - name: Life
              value: life
            - name: Love
              value: love
