name: Build and deploy Jekyll site to GitHub Pages

on: [push, pull_request]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install ruby-bundler
      - uses: limjh16/jekyll-action-ts@v2
